### ISSUE TITLE
awacs does not contain StringEquals class/function

### ISSUE THREAD

**Issue by castaway2000** [cloudtools/awacs#135]
StringEquals is referenced many times through the code but the function is no longer used. 
as seen in these examples: https://github.com/cloudtools/awacs/blob/7ff6195b1c63382de81a9dca619b57d37cd5746d/examples/s3.py#L7

and the description of how to use ConditionalElement here
https://github.com/cloudtools/awacs/blob/7ff6195b1c63382de81a9dca619b57d37cd5746d/awacs/aws.py#L90

How is this functions supposed to work? I saw it referenced in the _conditional_strings variable here: https://github.com/cloudtools/awacs/blob/7ff6195b1c63382de81a9dca619b57d37cd5746d/awacs/aws.py#L215

however I am not sure how i am supposed to use the following code to create the condition as it returns a NoneType Object when using it like so: make_condition('StringEquals', 'StringEquals')
https://github.com/cloudtools/awacs/blob/7ff6195b1c63382de81a9dca619b57d37cd5746d/awacs/aws.py#L229

the use of this conditional implementation is unclear or broken.

**Comment by markpeek** [comment]
Not sure I understand your comment about "no longer used" since it does appear [here](https://github.com/cloudtools/awacs/blob/7ff6195b1c63382de81a9dca619b57d37cd5746d/examples/s3.py#L23) off your first link.

The use of `make_condition()` is an internal helper to help create these Conditional constructs that map to the [IAM Conditional Operators](https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_elements_condition_operators.html).

You should use it like the first example you indicated by importing it directly and then as an implementation in your policy statement.

**Comment by castaway2000** [comment]
OK so I need to tell pycharm to ignore the error that it does not exist. thanks.
