### ISSUE TITLE
Stop caching propnames?

### ISSUE THREAD

**Issue by michael-k** [cloudtools/awacs#162]
I've noticed in troposphere that with `self.propnames = props.keys()` the object can no longer be pickled.

- Does `AWSObject` need to be able to be pickled?

- Is it even necessary to cache the keys?  `name in self.props` (`.keys()` is not necessary) should be just as fast as `name in self.propnames`.

I don't see a reason for caching here.

See https://github.com/cloudtools/awacs/commit/b4e4008f79ee3e08fb926e07e292b037491407c8#diff-7026bda438cf5fffa3496ee838ea9504d1962b37c3e1c573f34b09ebe4b4588cL21-R21

**Comment by zdot** [comment]
Our code uses `deepcopy` to create copies of Troposphere templates (including any awacs statements) that can be safely mutated for various purposes. Removing `list()` breaks this functionality for us (because of the pickling issue). Is it possible to restore the `list` call, or else get rid of the cache altogether as @michael-k suggests above?
